[workspace]
resolver = "2"

members = [
    "y2023"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
clap = {version = "4", features = ["derive"]}
regex = "1.10"
thiserror = "1.0.63"